REFUND_SELFDESTRUCT = 24000

MAX_REFUND_QUOTIENT = 2

QAUATA_KEYSTORE_CODE_MARK_PREFIX = b'QAUATA PUBLICKEY RAINBOW IA CIRCUMZENITH'
QAUATA_KEYSTORE_CODE_MARK_LENGTH = 40
QAUATA_KEYSTORE_CODE_LENGTH = QAUATA_KEYSTORE_CODE_MARK_LENGTH + 60192

GIBBS_GAS_LIMIT_MINIMUM = 5000000
GIBBS_GAS_LIMIT_MAXIMUM = 2 ** 63 -1
GIBBS_GAS_LIMIT_ADJUSTMENT_FACTOR = 1024
GIBBS_GENESIS_GAS_LIMIT = 5000000

GIBBS_DIFFICULTY_ADJUSTMENT_CUTOFF = 13
GIBBS_DIFFICULTY_MINIMUM = 2500
GIBBS_DIFFICULTY_ADJUSTOR = 1024

GIBBS_GAS_KEYSTORE = 1888888

EIP658_TRANSACTION_STATUS_CODE_FAILURE = b''
EIP658_TRANSACTION_STATUS_CODE_SUCCESS = b'\x01'
