HEISENBERG_DIFFICULTY_ADJUSTMENT_CUTOFF = 13
REFUND_SELFDESTRUCT = 24000

MAX_REFUND_QUOTIENT = 2

QAUATA_KEYSTORE_CODE_MARK_PREFIX = b'QAUATA PUBLICKEY RAINBOW IA CIRCUMZENITH'
QAUATA_KEYSTORE_CODE_MARK_LENGTH = 40
QAUATA_KEYSTORE_CODE_LENGTH = QAUATA_KEYSTORE_CODE_MARK_LENGTH + 60192
